name: Test Application
on: 
  pull_request:
    - master
    - develop
jobs:
  test-app:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4      
      - uses: actions/setup-node@v4
        working-directory: ./app
        with:
          node-version: 23.10.0
      - run: npm ci
        working-directory: ./app
      - run: npm test
        working-directory: ./app